### ISSUE TITLE
Make TensorFlow great again

### ISSUE THREAD

**Issue by liuzhanhao** [atlanta-anti-antenna-lab/BackImageGeneration#1]
Why use PyTorch for our model zoo but not TensorFlow? [TensorFlow Hub](https://www.tensorflow.org/beta/tutorials/images/hub_with_keras) has provided many ready-to-use image models. Also, by using TensorFlow, we can use the [Google Colab](https://colab.research.google.com/) for experiments, which provides free GPU/TPU.

Let's make TensorFlow great again!

**Comment by ZhuoranYu** [comment]
I think Google Colab also supports Pytorch maybe
